require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prescriptions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Prescription. As you add validations to Prescription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Prescription.create! valid_attributes
      get prescriptions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prescription = Prescription.create! valid_attributes
      get prescription_url(prescription)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prescription_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      prescription = Prescription.create! valid_attributes
      get edit_prescription_url(prescription)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Prescription" do
        expect {
          post prescriptions_url, params: { prescription: valid_attributes }
        }.to change(Prescription, :count).by(1)
      end

      it "redirects to the created prescription" do
        post prescriptions_url, params: { prescription: valid_attributes }
        expect(response).to redirect_to(prescription_url(Prescription.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Prescription" do
        expect {
          post prescriptions_url, params: { prescription: invalid_attributes }
        }.to change(Prescription, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post prescriptions_url, params: { prescription: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prescription" do
        prescription = Prescription.create! valid_attributes
        patch prescription_url(prescription), params: { prescription: new_attributes }
        prescription.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prescription" do
        prescription = Prescription.create! valid_attributes
        patch prescription_url(prescription), params: { prescription: new_attributes }
        prescription.reload
        expect(response).to redirect_to(prescription_url(prescription))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        prescription = Prescription.create! valid_attributes
        patch prescription_url(prescription), params: { prescription: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prescription" do
      prescription = Prescription.create! valid_attributes
      expect {
        delete prescription_url(prescription)
      }.to change(Prescription, :count).by(-1)
    end

    it "redirects to the prescriptions list" do
      prescription = Prescription.create! valid_attributes
      delete prescription_url(prescription)
      expect(response).to redirect_to(prescriptions_url)
    end
  end
end
